# Generated by Django 6.0.7 on 2026-07-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisenoSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sitio', models.CharField(default='Nebula', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='diseno/')),
                ('color_principal', models.CharField(default='#000000', max_length=7)),
            ],
        ),
    ]
